"""create activities and activity types tables

Revision ID: 3addbae61d47
Revises: 
Create Date: 2026-10-08 14:54:15.556227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3addbae61d47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tipos_actividad = op.create_table('tipos_actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('fecha_hora_postergada', sa.DateTime(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('cupo', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=500), nullable=False),
    sa.Column('frecuencia', sa.Enum('unica', 'semanal', 'quincenal', 'mensual', name='frecuenciaactividad', native_enum=False, length=20), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'cancelada', 'postergada', 'inactiva', name='estadoactividad', native_enum=False, length=20), nullable=False),
    sa.Column('edad_minima', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_actividad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actividades_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_actividades_fecha_hora'), ['fecha_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_actividades_tipo_id'), ['tipo_id'], unique=False)

    # ### end Alembic commands ###

    # Seed the initial activity types; more can be added later from the API
    op.bulk_insert(
        tipos_actividad,
        [{'nombre': nombre} for nombre in ('Taller', 'Torneo', 'Feria', 'Rol', 'Otro')],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actividades_tipo_id'))
        batch_op.drop_index(batch_op.f('ix_actividades_fecha_hora'))
        batch_op.drop_index(batch_op.f('ix_actividades_estado'))

    op.drop_table('actividades')
    op.drop_table('tipos_actividad')
    # ### end Alembic commands ###
