"""create manga comics table

Revision ID: b2da87f9bfe5
Revises: 
Create Date: 2026-10-09 01:06:31.820569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2da87f9bfe5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga_comics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('volume_number', sa.Integer(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('copies', sa.Integer(), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.CheckConstraint('copies > 0', name='ck_manga_comics_copies_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manga_comics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manga_comics_id'), ['id'], unique=False)
        batch_op.create_index('uq_manga_comics_title_volume_active', ['title', 'volume_number'], unique=True, postgresql_where=sa.text('is_active IS TRUE'), sqlite_where=sa.text('is_active = 1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_comics', schema=None) as batch_op:
        batch_op.drop_index('uq_manga_comics_title_volume_active', postgresql_where=sa.text('is_active IS TRUE'), sqlite_where=sa.text('is_active = 1'))
        batch_op.drop_index(batch_op.f('ix_manga_comics_id'))

    op.drop_table('manga_comics')
    # ### end Alembic commands ###
