"""add reason and scope to activities

Revision ID: c8014ea8ac35
Revises: 3addbae61d47
Create Date: 2026-10-09 10:26:55.741762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8014ea8ac35'
down_revision: Union[str, Sequence[str], None] = '3addbae61d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('alcance', sa.Enum('fecha', 'serie', name='alcancecambio', native_enum=False, length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.drop_column('alcance')
        batch_op.drop_column('motivo')

    # ### end Alembic commands ###
