"""crear tabla productos

Revision ID: ca8410f8b2df
Revises: 1a63a86717c0
Create Date: 2026-10-09 21:48:56.060519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8410f8b2df'
down_revision: Union[str, Sequence[str], None] = '1a63a86717c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('comida', 'bebida', 'snack', 'postre', 'combo', name='tipoproducto', native_enum=False, length=20), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.CheckConstraint('precio > 0', name='ck_productos_precio_positivo'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_tipo'))

    op.drop_table('productos')
    # ### end Alembic commands ###
