"""crear tablas de juegos, categorias, dificultades y reglas

Revision ID: f3812e8e60c9
Revises: 70020f699ab9
Create Date: 2026-10-09 00:55:25.931197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3812e8e60c9'
down_revision: Union[str, Sequence[str], None] = '70020f699ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_juego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('dificultades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('juegos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('disponibilidad', sa.Boolean(), nullable=False),
    sa.Column('duracion_min', sa.Integer(), nullable=False),
    sa.Column('edad_recomendada', sa.Integer(), nullable=False),
    sa.Column('jugadores_min', sa.Integer(), nullable=False),
    sa.Column('jugadores_max', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('dificultad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dificultad_id'], ['dificultades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('juegos_categorias',
    sa.Column('juego_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_juego.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['juego_id'], ['juegos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('juego_id', 'categoria_id')
    )
    op.create_table('reglas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('juego_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['juego_id'], ['juegos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reglas')
    op.drop_table('juegos_categorias')
    op.drop_table('juegos')
    op.drop_table('dificultades')
    op.drop_table('categorias_juego')
    # ### end Alembic commands ###
